### ISSUE TITLE
Jekyll not rendering properly

### ISSUE THREAD

**Issue by pickettj** [pickettj/jamespickett.info#1]
I must be pretty close to getting this working, since the site rendered fine serving Jekyll locally; but http://jamespickett.info/ is still not rendering properly. @OleVik , any chance you can tell me what I am doing wrong?

**Comment by OleVik** [comment]
Indeed, you are very close! If you open your browser's DevTools - generally by clicking the F12-key on your keyboard - you'll notice the following in the console:

```
GET http://jamespickett.info//imiml/assets/css/pure-drawer.css net::ERR_ABORTED 404 (Not Found)
GET http://jamespickett.info//imiml/assets/css/main.css net::ERR_ABORTED 404 (Not Found)
GET http://jamespickett.info//imiml/assets/css/modifications.css net::ERR_ABORTED 404 (Not Found)
GET http://jamespickett.info//imiml/assets/css/font/montserrat.css net::ERR_ABORTED 404 (Not Found)
```

This is because of how [head.html](https://github.com/pickettj/jamespickett.info/blob/master/_includes/head.html#L1-L15) is set up. One oddity is that `/imiml/` occurs in these URLs. Since your `baseurl` is [set to](https://github.com/pickettj/jamespickett.info/blob/master/_config.yml#L29) `"jamespickett.info"`, a CNAME, you'll want replace all instances of `./{{ site.baseurl }}/assets` with `/assets`.

That way they are domain-relative, and will automatically resolve to `jamespickett.info/assets/...`.

**Comment by pickettj** [comment]
Thank you, @OleVik !
